// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/banner.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Slot struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slot) Reset()         { *m = Slot{} }
func (m *Slot) String() string { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()    {}
func (*Slot) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b86f169d1f5a56, []int{0}
}

func (m *Slot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slot.Unmarshal(m, b)
}
func (m *Slot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slot.Marshal(b, m, deterministic)
}
func (m *Slot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slot.Merge(m, src)
}
func (m *Slot) XXX_Size() int {
	return xxx_messageInfo_Slot.Size(m)
}
func (m *Slot) XXX_DiscardUnknown() {
	xxx_messageInfo_Slot.DiscardUnknown(m)
}

var xxx_messageInfo_Slot proto.InternalMessageInfo

func (m *Slot) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Audience struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Audience) Reset()         { *m = Audience{} }
func (m *Audience) String() string { return proto.CompactTextString(m) }
func (*Audience) ProtoMessage()    {}
func (*Audience) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b86f169d1f5a56, []int{1}
}

func (m *Audience) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audience.Unmarshal(m, b)
}
func (m *Audience) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audience.Marshal(b, m, deterministic)
}
func (m *Audience) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audience.Merge(m, src)
}
func (m *Audience) XXX_Size() int {
	return xxx_messageInfo_Audience.Size(m)
}
func (m *Audience) XXX_DiscardUnknown() {
	xxx_messageInfo_Audience.DiscardUnknown(m)
}

var xxx_messageInfo_Audience proto.InternalMessageInfo

func (m *Audience) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Banner struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Banner) Reset()         { *m = Banner{} }
func (m *Banner) String() string { return proto.CompactTextString(m) }
func (*Banner) ProtoMessage()    {}
func (*Banner) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b86f169d1f5a56, []int{2}
}

func (m *Banner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Banner.Unmarshal(m, b)
}
func (m *Banner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Banner.Marshal(b, m, deterministic)
}
func (m *Banner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Banner.Merge(m, src)
}
func (m *Banner) XXX_Size() int {
	return xxx_messageInfo_Banner.Size(m)
}
func (m *Banner) XXX_DiscardUnknown() {
	xxx_messageInfo_Banner.DiscardUnknown(m)
}

var xxx_messageInfo_Banner proto.InternalMessageInfo

func (m *Banner) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Date struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b86f169d1f5a56, []int{3}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type GetBannerRequestMessage struct {
	Audience             *Audience `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Slot                 *Slot     `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetBannerRequestMessage) Reset()         { *m = GetBannerRequestMessage{} }
func (m *GetBannerRequestMessage) String() string { return proto.CompactTextString(m) }
func (*GetBannerRequestMessage) ProtoMessage()    {}
func (*GetBannerRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b86f169d1f5a56, []int{4}
}

func (m *GetBannerRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBannerRequestMessage.Unmarshal(m, b)
}
func (m *GetBannerRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBannerRequestMessage.Marshal(b, m, deterministic)
}
func (m *GetBannerRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBannerRequestMessage.Merge(m, src)
}
func (m *GetBannerRequestMessage) XXX_Size() int {
	return xxx_messageInfo_GetBannerRequestMessage.Size(m)
}
func (m *GetBannerRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBannerRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetBannerRequestMessage proto.InternalMessageInfo

func (m *GetBannerRequestMessage) GetAudience() *Audience {
	if m != nil {
		return m.Audience
	}
	return nil
}

func (m *GetBannerRequestMessage) GetSlot() *Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

type GetBannerResponseMessage struct {
	Banner               *Banner  `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBannerResponseMessage) Reset()         { *m = GetBannerResponseMessage{} }
func (m *GetBannerResponseMessage) String() string { return proto.CompactTextString(m) }
func (*GetBannerResponseMessage) ProtoMessage()    {}
func (*GetBannerResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b86f169d1f5a56, []int{5}
}

func (m *GetBannerResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBannerResponseMessage.Unmarshal(m, b)
}
func (m *GetBannerResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBannerResponseMessage.Marshal(b, m, deterministic)
}
func (m *GetBannerResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBannerResponseMessage.Merge(m, src)
}
func (m *GetBannerResponseMessage) XXX_Size() int {
	return xxx_messageInfo_GetBannerResponseMessage.Size(m)
}
func (m *GetBannerResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBannerResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetBannerResponseMessage proto.InternalMessageInfo

func (m *GetBannerResponseMessage) GetBanner() *Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

func init() {
	proto.RegisterType((*Slot)(nil), "proto.Slot")
	proto.RegisterType((*Audience)(nil), "proto.Audience")
	proto.RegisterType((*Banner)(nil), "proto.Banner")
	proto.RegisterType((*Date)(nil), "proto.Date")
	proto.RegisterType((*GetBannerRequestMessage)(nil), "proto.GetBannerRequestMessage")
	proto.RegisterType((*GetBannerResponseMessage)(nil), "proto.GetBannerResponseMessage")
}

func init() { proto.RegisterFile("proto/banner.proto", fileDescriptor_45b86f169d1f5a56) }

var fileDescriptor_45b86f169d1f5a56 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x69, 0x89, 0xb1, 0x4c, 0xa9, 0xc2, 0x1e, 0x6a, 0xc8, 0xc1, 0x48, 0x40, 0x10, 0x84,
	0x0d, 0x54, 0xf0, 0xde, 0xaa, 0x78, 0xf2, 0x92, 0x7a, 0xd1, 0xdb, 0xa6, 0x3b, 0x86, 0x95, 0x74,
	0x37, 0x66, 0x27, 0xfd, 0xfd, 0xe2, 0xee, 0xa6, 0x28, 0xc1, 0xd3, 0x30, 0x79, 0x2f, 0xef, 0x7d,
	0x93, 0x00, 0x6b, 0x3b, 0x43, 0xa6, 0xa8, 0x84, 0xd6, 0xd8, 0x71, 0xb7, 0xb0, 0x13, 0x37, 0xd2,
	0xac, 0x36, 0xa6, 0x6e, 0xb0, 0x70, 0x5b, 0xd5, 0x7f, 0x14, 0xa4, 0xf6, 0x68, 0x49, 0xec, 0x5b,
	0xef, 0xcb, 0x97, 0x10, 0x6d, 0x1b, 0x43, 0xec, 0x0c, 0xa6, 0x4a, 0x26, 0x93, 0xab, 0xc9, 0x4d,
	0x54, 0x4e, 0x95, 0xcc, 0x53, 0x98, 0xad, 0x7b, 0xa9, 0x50, 0xef, 0x70, 0xa4, 0x25, 0x10, 0x6f,
	0x5c, 0xd7, 0x48, 0xb9, 0x87, 0xe8, 0x51, 0x10, 0x32, 0x0e, 0x91, 0x14, 0x84, 0x4e, 0x99, 0xaf,
	0x52, 0xee, 0x29, 0xf8, 0x40, 0xc1, 0x5f, 0x07, 0x8a, 0xd2, 0xf9, 0xf2, 0x1a, 0x2e, 0x9e, 0x91,
	0x7c, 0x68, 0x89, 0x5f, 0x3d, 0x5a, 0x7a, 0x41, 0x6b, 0x45, 0x8d, 0xec, 0x16, 0x66, 0x22, 0x80,
	0x84, 0xb8, 0x73, 0x9f, 0xc3, 0x07, 0xbe, 0xf2, 0x68, 0x60, 0x19, 0x44, 0xb6, 0x31, 0x94, 0x4c,
	0x9d, 0x71, 0x1e, 0x8c, 0x3f, 0x07, 0x96, 0x4e, 0xc8, 0xd7, 0x90, 0xfc, 0x2a, 0xb2, 0xad, 0xd1,
	0x16, 0x87, 0xa6, 0x6b, 0x88, 0xfd, 0x27, 0x0c, 0x3d, 0x8b, 0xf0, 0x7a, 0x70, 0x07, 0x71, 0xf5,
	0x09, 0x0b, 0xff, 0x64, 0x8b, 0xdd, 0x41, 0xed, 0x90, 0xbd, 0xc1, 0xd2, 0xa2, 0x96, 0x0f, 0x1d,
	0x0a, 0xc2, 0xa7, 0x03, 0xea, 0x23, 0xfb, 0x65, 0x48, 0xf8, 0xe7, 0xb6, 0x34, 0x1b, 0xeb, 0x7f,
	0x90, 0x36, 0xa7, 0xef, 0xfe, 0x3f, 0x56, 0xb1, 0x1b, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb7, 0xe7, 0xe6, 0x2a, 0xeb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BannerServiceClient is the client API for BannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BannerServiceClient interface {
	SendCreateEventMessage(ctx context.Context, in *GetBannerRequestMessage, opts ...grpc.CallOption) (*GetBannerResponseMessage, error)
}

type bannerServiceClient struct {
	cc *grpc.ClientConn
}

func NewBannerServiceClient(cc *grpc.ClientConn) BannerServiceClient {
	return &bannerServiceClient{cc}
}

func (c *bannerServiceClient) SendCreateEventMessage(ctx context.Context, in *GetBannerRequestMessage, opts ...grpc.CallOption) (*GetBannerResponseMessage, error) {
	out := new(GetBannerResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.BannerService/sendCreateEventMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannerServiceServer is the server API for BannerService service.
type BannerServiceServer interface {
	SendCreateEventMessage(context.Context, *GetBannerRequestMessage) (*GetBannerResponseMessage, error)
}

// UnimplementedBannerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBannerServiceServer struct {
}

func (*UnimplementedBannerServiceServer) SendCreateEventMessage(ctx context.Context, req *GetBannerRequestMessage) (*GetBannerResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCreateEventMessage not implemented")
}

func RegisterBannerServiceServer(s *grpc.Server, srv BannerServiceServer) {
	s.RegisterService(&_BannerService_serviceDesc, srv)
}

func _BannerService_SendCreateEventMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannerRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).SendCreateEventMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/SendCreateEventMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).SendCreateEventMessage(ctx, req.(*GetBannerRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _BannerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BannerService",
	HandlerType: (*BannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendCreateEventMessage",
			Handler:    _BannerService_SendCreateEventMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/banner.proto",
}
