// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/banner.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Slot struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Slot) Reset()         { *m = Slot{} }
func (m *Slot) String() string { return proto.CompactTextString(m) }
func (*Slot) ProtoMessage()    {}
func (*Slot) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{0}
}

func (m *Slot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Slot.Unmarshal(m, b)
}
func (m *Slot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Slot.Marshal(b, m, deterministic)
}
func (m *Slot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Slot.Merge(m, src)
}
func (m *Slot) XXX_Size() int {
	return xxx_messageInfo_Slot.Size(m)
}
func (m *Slot) XXX_DiscardUnknown() {
	xxx_messageInfo_Slot.DiscardUnknown(m)
}

var xxx_messageInfo_Slot proto.InternalMessageInfo

func (m *Slot) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Audience struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Audience) Reset()         { *m = Audience{} }
func (m *Audience) String() string { return proto.CompactTextString(m) }
func (*Audience) ProtoMessage()    {}
func (*Audience) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{1}
}

func (m *Audience) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audience.Unmarshal(m, b)
}
func (m *Audience) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audience.Marshal(b, m, deterministic)
}
func (m *Audience) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audience.Merge(m, src)
}
func (m *Audience) XXX_Size() int {
	return xxx_messageInfo_Audience.Size(m)
}
func (m *Audience) XXX_DiscardUnknown() {
	xxx_messageInfo_Audience.DiscardUnknown(m)
}

var xxx_messageInfo_Audience proto.InternalMessageInfo

func (m *Audience) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Banner struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Banner) Reset()         { *m = Banner{} }
func (m *Banner) String() string { return proto.CompactTextString(m) }
func (*Banner) ProtoMessage()    {}
func (*Banner) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{2}
}

func (m *Banner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Banner.Unmarshal(m, b)
}
func (m *Banner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Banner.Marshal(b, m, deterministic)
}
func (m *Banner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Banner.Merge(m, src)
}
func (m *Banner) XXX_Size() int {
	return xxx_messageInfo_Banner.Size(m)
}
func (m *Banner) XXX_DiscardUnknown() {
	xxx_messageInfo_Banner.DiscardUnknown(m)
}

var xxx_messageInfo_Banner proto.InternalMessageInfo

func (m *Banner) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Date struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{3}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type Response struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResponseBannerMessage struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResponseBannerMessage) Reset()         { *m = ResponseBannerMessage{} }
func (m *ResponseBannerMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseBannerMessage) ProtoMessage()    {}
func (*ResponseBannerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{5}
}

func (m *ResponseBannerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseBannerMessage.Unmarshal(m, b)
}
func (m *ResponseBannerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseBannerMessage.Marshal(b, m, deterministic)
}
func (m *ResponseBannerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseBannerMessage.Merge(m, src)
}
func (m *ResponseBannerMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseBannerMessage.Size(m)
}
func (m *ResponseBannerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseBannerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseBannerMessage proto.InternalMessageInfo

func (m *ResponseBannerMessage) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type GetBannerRequestMessage struct {
	Audience             *Audience `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Slot                 *Slot     `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetBannerRequestMessage) Reset()         { *m = GetBannerRequestMessage{} }
func (m *GetBannerRequestMessage) String() string { return proto.CompactTextString(m) }
func (*GetBannerRequestMessage) ProtoMessage()    {}
func (*GetBannerRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{6}
}

func (m *GetBannerRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBannerRequestMessage.Unmarshal(m, b)
}
func (m *GetBannerRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBannerRequestMessage.Marshal(b, m, deterministic)
}
func (m *GetBannerRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBannerRequestMessage.Merge(m, src)
}
func (m *GetBannerRequestMessage) XXX_Size() int {
	return xxx_messageInfo_GetBannerRequestMessage.Size(m)
}
func (m *GetBannerRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBannerRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetBannerRequestMessage proto.InternalMessageInfo

func (m *GetBannerRequestMessage) GetAudience() *Audience {
	if m != nil {
		return m.Audience
	}
	return nil
}

func (m *GetBannerRequestMessage) GetSlot() *Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

type GetBannerResponseMessage struct {
	Banner               *Banner  `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBannerResponseMessage) Reset()         { *m = GetBannerResponseMessage{} }
func (m *GetBannerResponseMessage) String() string { return proto.CompactTextString(m) }
func (*GetBannerResponseMessage) ProtoMessage()    {}
func (*GetBannerResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{7}
}

func (m *GetBannerResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBannerResponseMessage.Unmarshal(m, b)
}
func (m *GetBannerResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBannerResponseMessage.Marshal(b, m, deterministic)
}
func (m *GetBannerResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBannerResponseMessage.Merge(m, src)
}
func (m *GetBannerResponseMessage) XXX_Size() int {
	return xxx_messageInfo_GetBannerResponseMessage.Size(m)
}
func (m *GetBannerResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBannerResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetBannerResponseMessage proto.InternalMessageInfo

func (m *GetBannerResponseMessage) GetBanner() *Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

type AddBannerToSlotRequestMessage struct {
	Audience             *Audience `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Slot                 *Slot     `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddBannerToSlotRequestMessage) Reset()         { *m = AddBannerToSlotRequestMessage{} }
func (m *AddBannerToSlotRequestMessage) String() string { return proto.CompactTextString(m) }
func (*AddBannerToSlotRequestMessage) ProtoMessage()    {}
func (*AddBannerToSlotRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{8}
}

func (m *AddBannerToSlotRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBannerToSlotRequestMessage.Unmarshal(m, b)
}
func (m *AddBannerToSlotRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBannerToSlotRequestMessage.Marshal(b, m, deterministic)
}
func (m *AddBannerToSlotRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBannerToSlotRequestMessage.Merge(m, src)
}
func (m *AddBannerToSlotRequestMessage) XXX_Size() int {
	return xxx_messageInfo_AddBannerToSlotRequestMessage.Size(m)
}
func (m *AddBannerToSlotRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBannerToSlotRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AddBannerToSlotRequestMessage proto.InternalMessageInfo

func (m *AddBannerToSlotRequestMessage) GetAudience() *Audience {
	if m != nil {
		return m.Audience
	}
	return nil
}

func (m *AddBannerToSlotRequestMessage) GetSlot() *Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

type DeleteBannerFromSlotRequestMessage struct {
	Audience             *Audience `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Slot                 *Slot     `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeleteBannerFromSlotRequestMessage) Reset()         { *m = DeleteBannerFromSlotRequestMessage{} }
func (m *DeleteBannerFromSlotRequestMessage) String() string { return proto.CompactTextString(m) }
func (*DeleteBannerFromSlotRequestMessage) ProtoMessage()    {}
func (*DeleteBannerFromSlotRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{9}
}

func (m *DeleteBannerFromSlotRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBannerFromSlotRequestMessage.Unmarshal(m, b)
}
func (m *DeleteBannerFromSlotRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBannerFromSlotRequestMessage.Marshal(b, m, deterministic)
}
func (m *DeleteBannerFromSlotRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBannerFromSlotRequestMessage.Merge(m, src)
}
func (m *DeleteBannerFromSlotRequestMessage) XXX_Size() int {
	return xxx_messageInfo_DeleteBannerFromSlotRequestMessage.Size(m)
}
func (m *DeleteBannerFromSlotRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBannerFromSlotRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBannerFromSlotRequestMessage proto.InternalMessageInfo

func (m *DeleteBannerFromSlotRequestMessage) GetAudience() *Audience {
	if m != nil {
		return m.Audience
	}
	return nil
}

func (m *DeleteBannerFromSlotRequestMessage) GetSlot() *Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

type AddClickRequestMessage struct {
	Banner               *Banner   `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	Slot                 *Slot     `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Audience             *Audience `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddClickRequestMessage) Reset()         { *m = AddClickRequestMessage{} }
func (m *AddClickRequestMessage) String() string { return proto.CompactTextString(m) }
func (*AddClickRequestMessage) ProtoMessage()    {}
func (*AddClickRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3ffd83f03c6cb78, []int{10}
}

func (m *AddClickRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClickRequestMessage.Unmarshal(m, b)
}
func (m *AddClickRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClickRequestMessage.Marshal(b, m, deterministic)
}
func (m *AddClickRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClickRequestMessage.Merge(m, src)
}
func (m *AddClickRequestMessage) XXX_Size() int {
	return xxx_messageInfo_AddClickRequestMessage.Size(m)
}
func (m *AddClickRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClickRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AddClickRequestMessage proto.InternalMessageInfo

func (m *AddClickRequestMessage) GetBanner() *Banner {
	if m != nil {
		return m.Banner
	}
	return nil
}

func (m *AddClickRequestMessage) GetSlot() *Slot {
	if m != nil {
		return m.Slot
	}
	return nil
}

func (m *AddClickRequestMessage) GetAudience() *Audience {
	if m != nil {
		return m.Audience
	}
	return nil
}

func init() {
	proto.RegisterType((*Slot)(nil), "proto.Slot")
	proto.RegisterType((*Audience)(nil), "proto.Audience")
	proto.RegisterType((*Banner)(nil), "proto.Banner")
	proto.RegisterType((*Date)(nil), "proto.Date")
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*ResponseBannerMessage)(nil), "proto.ResponseBannerMessage")
	proto.RegisterType((*GetBannerRequestMessage)(nil), "proto.GetBannerRequestMessage")
	proto.RegisterType((*GetBannerResponseMessage)(nil), "proto.GetBannerResponseMessage")
	proto.RegisterType((*AddBannerToSlotRequestMessage)(nil), "proto.AddBannerToSlotRequestMessage")
	proto.RegisterType((*DeleteBannerFromSlotRequestMessage)(nil), "proto.DeleteBannerFromSlotRequestMessage")
	proto.RegisterType((*AddClickRequestMessage)(nil), "proto.AddClickRequestMessage")
}

func init() { proto.RegisterFile("api/proto/banner.proto", fileDescriptor_a3ffd83f03c6cb78) }

var fileDescriptor_a3ffd83f03c6cb78 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0xa5, 0x7d, 0x31, 0xaf, 0xde, 0xf2, 0x14, 0x06, 0x8d, 0x31, 0xf8, 0x8c, 0x0c, 0x0a, 0x8a,
	0x90, 0x42, 0x05, 0x57, 0x6e, 0xf2, 0x2c, 0xba, 0x72, 0x93, 0x16, 0x14, 0x57, 0xa6, 0x9d, 0x6b,
	0x88, 0x26, 0x99, 0x98, 0x99, 0xf8, 0x2f, 0x04, 0x7f, 0xb2, 0x74, 0x3e, 0x6a, 0x93, 0xd6, 0xc6,
	0x4d, 0x57, 0x61, 0x7a, 0xce, 0x9c, 0x73, 0xe6, 0x9e, 0x4b, 0xc1, 0x4b, 0xeb, 0x7c, 0x56, 0x37,
	0x5c, 0xf2, 0xd9, 0x3a, 0xad, 0x2a, 0x6c, 0x22, 0x75, 0x20, 0xb7, 0xd4, 0x27, 0x08, 0x33, 0xce,
	0xb3, 0x02, 0x35, 0x63, 0xdd, 0x7e, 0x9d, 0xc9, 0xbc, 0x44, 0x21, 0xd3, 0xb2, 0xd6, 0x3c, 0xea,
	0x81, 0xb3, 0x2c, 0xb8, 0x24, 0x77, 0x60, 0x9c, 0x33, 0x7f, 0xf4, 0x64, 0xf4, 0xfc, 0x76, 0x32,
	0xce, 0x19, 0x0d, 0x60, 0x12, 0xb7, 0x2c, 0xc7, 0x6a, 0x83, 0x07, 0x98, 0x0f, 0xee, 0x8d, 0xf2,
	0x3a, 0x40, 0x5e, 0x83, 0xb3, 0x48, 0x25, 0x92, 0x08, 0x1c, 0x96, 0x4a, 0x54, 0xc8, 0x74, 0x1e,
	0x44, 0x3a, 0x45, 0x64, 0x53, 0x44, 0x2b, 0x9b, 0x22, 0x51, 0x3c, 0xfa, 0x06, 0x26, 0x09, 0x8a,
	0x9a, 0x57, 0x02, 0x89, 0x07, 0x6e, 0x83, 0xa2, 0x2d, 0xa4, 0xd1, 0x35, 0x27, 0xe2, 0xc3, 0x65,
	0x89, 0x42, 0xa4, 0x19, 0xfa, 0x63, 0x05, 0xd8, 0x23, 0x5d, 0xc0, 0x7d, 0x7b, 0x5b, 0xe7, 0xfa,
	0xa0, 0x01, 0xf2, 0x12, 0x26, 0x8d, 0x01, 0x4c, 0x94, 0xbb, 0x3a, 0x43, 0x64, 0xf9, 0xc9, 0x8e,
	0x40, 0x33, 0x78, 0xf0, 0x1e, 0xa5, 0x16, 0x48, 0xf0, 0x47, 0x8b, 0x42, 0xee, 0xe9, 0xa4, 0x66,
	0x18, 0x3d, 0x1d, 0x3b, 0xa3, 0x64, 0x47, 0x20, 0x21, 0x38, 0xa2, 0xe0, 0x52, 0x85, 0x9c, 0xce,
	0xa7, 0x86, 0xb8, 0x1d, 0x72, 0xa2, 0x00, 0x1a, 0x83, 0xbf, 0x67, 0xa4, 0xdd, 0xad, 0xd3, 0x33,
	0x70, 0x75, 0x8d, 0xc6, 0xe7, 0xca, 0x5c, 0x37, 0x6c, 0x03, 0xd2, 0x12, 0xae, 0x63, 0xc6, 0xf4,
	0x8f, 0x2b, 0xae, 0xb4, 0xcf, 0x99, 0xb8, 0x01, 0xba, 0xc0, 0x02, 0xa5, 0x19, 0xef, 0xbb, 0x86,
	0x97, 0x67, 0xf7, 0xfc, 0x35, 0x02, 0x2f, 0x66, 0xec, 0x6d, 0x91, 0x6f, 0xbe, 0xf7, 0x8c, 0xfe,
	0x6f, 0x48, 0x83, 0x16, 0x9d, 0xc0, 0x17, 0x03, 0x81, 0xe7, 0xbf, 0x2f, 0xe0, 0x4a, 0x1b, 0x2c,
	0xb1, 0xf9, 0x99, 0x6f, 0x90, 0x7c, 0x84, 0x7b, 0x02, 0x2b, 0xb6, 0xeb, 0xd2, 0xc6, 0x7b, 0x6c,
	0x44, 0xfe, 0xb1, 0x4d, 0x41, 0x78, 0x88, 0x77, 0x97, 0xe0, 0x0b, 0x04, 0x5b, 0xe1, 0x5e, 0xc3,
	0x16, 0x7d, 0x6a, 0x33, 0x9e, 0x5a, 0x80, 0xe0, 0x51, 0x6f, 0xd1, 0xbb, 0x11, 0xbf, 0x41, 0xb8,
	0x75, 0x38, 0x56, 0xaa, 0xa5, 0xbc, 0x30, 0x02, 0xc3, 0xc5, 0x0f, 0x78, 0x7d, 0x82, 0x87, 0xe6,
	0x35, 0xaa, 0xcb, 0x2e, 0x78, 0xfd, 0xf7, 0x31, 0x47, 0x9a, 0x3e, 0xad, 0x7c, 0x73, 0xf9, 0x59,
	0xff, 0xcb, 0xad, 0x5d, 0xf5, 0x79, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xa1, 0xd4, 0x93,
	0x0d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BannerServiceClient is the client API for BannerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BannerServiceClient interface {
	SendGetBannerMessage(ctx context.Context, in *GetBannerRequestMessage, opts ...grpc.CallOption) (*GetBannerResponseMessage, error)
	SendAddBannerToSlotMessage(ctx context.Context, in *AddBannerToSlotRequestMessage, opts ...grpc.CallOption) (*ResponseBannerMessage, error)
	SendDeleteBannerFromSlotMessage(ctx context.Context, in *DeleteBannerFromSlotRequestMessage, opts ...grpc.CallOption) (*ResponseBannerMessage, error)
	SendAddClickBannerMessage(ctx context.Context, in *AddClickRequestMessage, opts ...grpc.CallOption) (*ResponseBannerMessage, error)
}

type bannerServiceClient struct {
	cc *grpc.ClientConn
}

func NewBannerServiceClient(cc *grpc.ClientConn) BannerServiceClient {
	return &bannerServiceClient{cc}
}

func (c *bannerServiceClient) SendGetBannerMessage(ctx context.Context, in *GetBannerRequestMessage, opts ...grpc.CallOption) (*GetBannerResponseMessage, error) {
	out := new(GetBannerResponseMessage)
	err := c.cc.Invoke(ctx, "/proto.BannerService/sendGetBannerMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) SendAddBannerToSlotMessage(ctx context.Context, in *AddBannerToSlotRequestMessage, opts ...grpc.CallOption) (*ResponseBannerMessage, error) {
	out := new(ResponseBannerMessage)
	err := c.cc.Invoke(ctx, "/proto.BannerService/sendAddBannerToSlotMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) SendDeleteBannerFromSlotMessage(ctx context.Context, in *DeleteBannerFromSlotRequestMessage, opts ...grpc.CallOption) (*ResponseBannerMessage, error) {
	out := new(ResponseBannerMessage)
	err := c.cc.Invoke(ctx, "/proto.BannerService/sendDeleteBannerFromSlotMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerServiceClient) SendAddClickBannerMessage(ctx context.Context, in *AddClickRequestMessage, opts ...grpc.CallOption) (*ResponseBannerMessage, error) {
	out := new(ResponseBannerMessage)
	err := c.cc.Invoke(ctx, "/proto.BannerService/sendAddClickBannerMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannerServiceServer is the server API for BannerService service.
type BannerServiceServer interface {
	SendGetBannerMessage(context.Context, *GetBannerRequestMessage) (*GetBannerResponseMessage, error)
	SendAddBannerToSlotMessage(context.Context, *AddBannerToSlotRequestMessage) (*ResponseBannerMessage, error)
	SendDeleteBannerFromSlotMessage(context.Context, *DeleteBannerFromSlotRequestMessage) (*ResponseBannerMessage, error)
	SendAddClickBannerMessage(context.Context, *AddClickRequestMessage) (*ResponseBannerMessage, error)
}

// UnimplementedBannerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBannerServiceServer struct {
}

func (*UnimplementedBannerServiceServer) SendGetBannerMessage(ctx context.Context, req *GetBannerRequestMessage) (*GetBannerResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGetBannerMessage not implemented")
}
func (*UnimplementedBannerServiceServer) SendAddBannerToSlotMessage(ctx context.Context, req *AddBannerToSlotRequestMessage) (*ResponseBannerMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAddBannerToSlotMessage not implemented")
}
func (*UnimplementedBannerServiceServer) SendDeleteBannerFromSlotMessage(ctx context.Context, req *DeleteBannerFromSlotRequestMessage) (*ResponseBannerMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDeleteBannerFromSlotMessage not implemented")
}
func (*UnimplementedBannerServiceServer) SendAddClickBannerMessage(ctx context.Context, req *AddClickRequestMessage) (*ResponseBannerMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAddClickBannerMessage not implemented")
}

func RegisterBannerServiceServer(s *grpc.Server, srv BannerServiceServer) {
	s.RegisterService(&_BannerService_serviceDesc, srv)
}

func _BannerService_SendGetBannerMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBannerRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).SendGetBannerMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/SendGetBannerMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).SendGetBannerMessage(ctx, req.(*GetBannerRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_SendAddBannerToSlotMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBannerToSlotRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).SendAddBannerToSlotMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/SendAddBannerToSlotMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).SendAddBannerToSlotMessage(ctx, req.(*AddBannerToSlotRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_SendDeleteBannerFromSlotMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBannerFromSlotRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).SendDeleteBannerFromSlotMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/SendDeleteBannerFromSlotMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).SendDeleteBannerFromSlotMessage(ctx, req.(*DeleteBannerFromSlotRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BannerService_SendAddClickBannerMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClickRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServiceServer).SendAddClickBannerMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BannerService/SendAddClickBannerMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServiceServer).SendAddClickBannerMessage(ctx, req.(*AddClickRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _BannerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BannerService",
	HandlerType: (*BannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendGetBannerMessage",
			Handler:    _BannerService_SendGetBannerMessage_Handler,
		},
		{
			MethodName: "sendAddBannerToSlotMessage",
			Handler:    _BannerService_SendAddBannerToSlotMessage_Handler,
		},
		{
			MethodName: "sendDeleteBannerFromSlotMessage",
			Handler:    _BannerService_SendDeleteBannerFromSlotMessage_Handler,
		},
		{
			MethodName: "sendAddClickBannerMessage",
			Handler:    _BannerService_SendAddClickBannerMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/banner.proto",
}
